MINTSCAN_LABEL_ARCH = "arch"
MILLION = 1000000.0
EXP18 = 10 ** 18

MSG_TYPE_DELEGATE = "MsgDelegate"
MSG_TYPE_EXECUTE_CONTRACT = "MsgExecuteContract"
MSG_TYPE_IBC_TRANSFER = "MsgTransfer"


MSG_TYPE_MSGRECVPACKET = "MsgRecvPacket"
MSG_TYPE_REDELEGATE = "MsgBeginRedelegate"
MSG_TYPE_SEND = "MsgSend"
MSG_TYPE_SET_WITHDRAW_ADDRESS = "MsgSetWithdrawAddress"
MSG_TYPE_SUBMIT_PROPOSAL = "MsgSubmitProposal"
MSG_TYPE_SWAP_IN = "MsgSwapExactAmountIn"
MSG_TYPE_SPLIT_ROUTE_SWAP = "MsgSplitRouteSwapExactAmountIn"
MSG_TYPE_SUPERFLUID_DELEGATE = "MsgSuperfluidDelegate"
MSG_TYPE_SUPERFLUID_UNDELEGATE = "MsgSuperfluidUndelegate"
MSG_TYPE_SUPERFLUID_UNBOND_LOCK = "MsgSuperfluidUnbondLock"
MSG_TYPE_TIMEOUT = "MsgTimeout"
MSG_TYPE_UNDELEGATE = "MsgUndelegate"
MSG_TYPE_UNLOCK_PERIOD_LOCK = "MsgUnlockPeriodLock"
MSG_TYPE_UPDATE_CLIENT = "MsgUpdateClient"
MSG_TYPE_VOTE = "MsgVote"
MSG_TYPE_WITHDRAW_COMMISSION = "MsgWithdrawValidatorCommission"
MSG_TYPE_WITHDRAW_POSITION = "MsgWithdrawPosition"
MSG_TYPE_WITHDRAW_REWARD = "MsgWithdrawDelegatorReward"